### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by haibianshifeng** [sorush-khajepor/listLBM#1]
[  2%] Building Fortran object tools/CMakeFiles/tools.dir/utility_mod.f90.o
/home/lei/listLBM/tools/utility_mod.f90:25.43:

        character(len=:),allocatable :: mem
                                           1
Error: Deferred-length character component 'mem' at (1) is not yet supported
make[2]: *** [tools/CMakeFiles/tools.dir/utility_mod.f90.o] 错误 1
make[1]: *** [tools/CMakeFiles/tools.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by sorush-khajepor** [comment]
The feature, deferred-length character, is not supported in the older GFortran versions. Make sure you use GFortran version 5 or higher. ListLBM is written with the latest Fortran standards (Fortran2003&2008).
